### MISC CONFIGS ###
# enable mouse control
set -g mouse on

# start index at 1
set -g base-index 1

# color
set -g default-terminal "screen-256color"

# clipboard
set -s set-clipboard on
set -as terminal-features ',screen-256color:clipboard'

# easy reload of config file
bind r source-file ~/.tmux.conf

# set-option -g status-position top

# change prefix from C-b to C-e
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

### PANES ###
# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim like pane switching
bind -r ^ last-window
bind -r h select-pane -L
bind -r s select-pane -R
bind -r t select-pane -U
bind -r n select-pane -D

# j<->t swap
bind-key -T copy-mode-vi t send-keys -X cursor-up
bind-key -T copy-mode-vi j command-prompt -1 -p "(jump to forward)" { send-keys -X jump-to-forward -- "%%" }

# J<->T swap
bind-key -T copy-mode-vi T send-keys -X scroll-up
bind-key -T copy-mode-vi J command-prompt -1 -p "(jump to backward)" { send-keys -X jump-to-backward -- "%%" }

# k<->n swap
bind-key -T copy-mode-vi n send-keys -X cursor-down
bind-key -T copy-mode-vi k send-keys -X search-again

# K<->N swap
bind-key -T copy-mode-vi N send-keys -X scroll-down
bind-key -T copy-mode-vi K send-keys -X search-reverse

bind-key -T copy-mode-vi s send-keys -X cursor-right

# increase pane num display time
set -g display-panes-time 4000

set -g status-style 'bg=#4a9e4e fg=black'
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=#4a9e4e'
set-option -g mode-style 'bg=#4a9e4e fg=black'

# increase scroll buffer size
set-option -g history-limit 100000

### STATUS BAR ###
# set 24 hour clock on right side of status bar
set-option -g status-right "%H:%M:%S 20%y-%m-%d #(~/scripts/batt.sh)"

set -g status-left-length 20

#set-option -g set-titles on
#set-option -g set-titles-string "#S"  # Use session name as title
set -g status-interval 1
