volnorm = true
hide_display_names = true
flip_status_indicators = true
use_nerdfont = false

[keybindings]
"l" = "save"
"s" = "move right 1"


# bright red
#[theme]
#background = "#000000"
#primary = "#FFFFFF"
#secondary = "#FFFFFF"
#title = "#FF0000"
#playing = "#FF0000"
#playing_selected = "#FFFFFF"
#playing_bg = "#000000"
#highlight = "#FFFFFF"
#highlight_bg = "#FF0000"
#error = "#FF0000"
#error_bg = "#A50000"
#statusbar = "#000000"
#statusbar_progress = "#FF0000"
#statusbar_bg = "#FFFFFF"
#cmdline = "#CBFFDE"
#cmdline_bg = "#444444"

# dark red
[theme]
background = "#000000"
primary = "#FFFFFF"
secondary = "#FFFFFF"
title = "#A50000"
playing = "#FF0000"
playing_selected = "#FFFFFF"
playing_bg = "#000000"
highlight = "#FFFFFF"
highlight_bg = "#A50000"
error = "#A50000"
error_bg = "#A50000"
statusbar = "#FFFFFF"
statusbar_progress = "#FF0000"
statusbar_bg = "000000"
#statusbar_bg = "green" <- exactly like tmux green
cmdline = "#CBFFDE"
cmdline_bg = "#444444"
