volnorm = true
hide_display_names = true
flip_status_indicators = true
use_nerdfont = false

[keybindings]
"l" = "save"
"s" = "move right 1"
"t" = "move up 1"
"n" = "move down 1"
"k" = "jumpnext"
"j" = ""


# bright red
#[theme]
#background = "#000000"
#primary = "#FFFFFF"
#secondary = "#FFFFFF"
#title = "#FF0000"
#playing = "#FF0000"
#playing_selected = "#FFFFFF"
#playing_bg = "#000000"
#highlight = "#FFFFFF"
#highlight_bg = "#FF0000"
#error = "#FF0000"
#error_bg = "#A50000"
#statusbar = "#000000"
#statusbar_progress = "#FF0000"
#statusbar_bg = "#FFFFFF"
#cmdline = "#CBFFDE"
#cmdline_bg = "#444444"

# dark red
#[theme]
#background = "#000000"
#primary = "#FFFFFF"
#secondary = "#FFFFFF"
#title = "#A50000"
#playing = "#FF0000"
#playing_selected = "#FFFFFF"
#playing_bg = "#000000"
#highlight = "#FFFFFF"
#highlight_bg = "#A50000"
#error = "#A50000"
#error_bg = "#A50000"
#statusbar = "#FFFFFF"
#statusbar_progress = "#FF0000"
#statusbar_bg = "000000"
###statusbar_bg = "green" <- exactly like tmux green
#cmdline = "#CBFFDE"
#cmdline_bg = "#444444"

# lilac
[theme]
background = "#1C1C1C"
primary = "#F1F1F1"
secondary = "#8D6CA5"
title = "#8D6CA5"
playing = "#9E19FF"
playing_selected = "#000000"
playing_bg = "#1C1C1C"
highlight = "#000000"
highlight_bg = "#8D6CA5"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#FFFFFF"
statusbar_progress = "#9E19FF"
statusbar_bg = "#8D6CA5"
cmdline = "#FFFFFF"
cmdline_bg = "#444444"
