volnorm = true
hide_display_names = true
flip_status_indicators = true
use_nerdfont = false

[keybindings]
"l" = "save"
"s" = "move right 1"


#[theme]
#background = "black"
#primary = "light white"
#secondary = "light black"
#title = "green"
#playing = "green"
#playing_selected = "light green"
#playing_bg = "black"
#highlight = "light white"
#highlight_bg = "#484848"
#error = "light white"
#error_bg = "red"
#statusbar = "black"
#statusbar_progress = "green"
#statusbar_bg = "green"
#cmdline = "light white"
#cmdline_bg = "black"
#search_match = "light red"



[theme]
background = "#000000"
primary = "#FFFFFF"
secondary = "#FFFFFF"
title = "#FF0000"
playing = "#FF0000"
playing_selected = "#FFFFFF"
playing_bg = "#000000"
highlight = "#FFFFFF"
highlight_bg = "#FF0000"
error = "#FF0000"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#FF0000"
statusbar_bg = "#FFFFFF"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"

